### ISSUE TITLE
phone connection to proxy issues

### ISSUE THREAD

**Issue by szomo** [plamoni/SiriProxy#16]
I hope im not missing something , the server seems to be running now but after loading the certificate onto my phone do i need to browse to an address to connect it somehow ? right now nothing transmits. i feel like im missing something obvious.

**Comment by plamoni** [comment]
DNS server is probably it.

Check: http://www.youtube.com/watch?v=a9gO4L0U59s

**Comment by netpro2k** [comment]
You need to have your phone set to point to your dnsmasq server for dns, so that when it requests guzzoni.apple.com it gets your proxy server's address instead. Depending on how you have your network setup, this could be done automatically for you through dhcp. If not you can always set it manually in wifi settings.
