### ISSUE TITLE
siriproxy update

### ISSUE THREAD

**Issue by JBX028** [plamoni/SiriProxy#163]
Hi,

I have installed siriproxy and dnsmasq under my virtual machne and i am able to capture the traffic between my iphone and the server.

What i did first, was to extend the siriproxy-example.rb in order to verify if the changes are taken into account before to move to the creation of a fresh plugin.

I added the following piece of script: 

``` ruby
listen_for /Bonjour/i do
  say "hello"
  request_completed
end
```

Afterward i have regenerated the gems (siriproxy update + my siriproxy directory) and restarded siriproxy.

When i say "Bonjour", the pattern is not captured. I can see "no match found for Bonjour". Do you know why ? Did i forgot something ?

Thanks!

**Comment by neoflex** [comment]
same problem for me. I am modifying the siriproxy-example.rb file but I can't see any changes. Is there any command we have to run to apply the changes? To recompile the plugin or something?

**Comment by gotnull** [comment]
I'm getting the exact same problem. I'm modifying the existing siriproxy-example.rb and running (siriproxy update) and she's not responding to the text I've modified. Is there a step we're missing?

**Comment by neoflex** [comment]
rake install in the SiriProxy folder solved the problem for me. You
are probably not modifying the files actually used (.rvm/.....)

Le 12 déc. 2011 à 23:48, Rakusu Digital Pty Ltd
reply@reply.github.com
a écrit :

**Comment by gotnull** [comment]
Oh, okay. So you're meant to modify the .rb files in ~/.rvm/ instead of ~/SiriProxy/plugins/siriproxy-example/lib/?

**Comment by muhkuh0815** [comment]
i think the real siriproxy-example.rb  is in the user/xxx/.rvm/gems/ruby193/gems/siriproxy030/plugins/   folder
at least on my messed up mac ...

so the easiest way is to change the  config.yml file   in the  hidden  user/xxx/ .siriproxy
just replace the path to   "/Users/xxx/SiriProxy/plugins/siriproxy-example" 

now it should use your edited file 

---

or you make a new plugin (you probably need it anyhow soon)

duplicate the siriproxy-example folder in your  user/xxx/SiriProxy/plugins  folder

rename the folder to lets say  siriproxy-test
rename the siriproxy-example.gemspec to siriproxy-test.gemspec  
open it 
replace the 2 "siriproxy-example" with "siriproxy-test"
save

then edit the  config.yml  in the hidden   /user/xxx/.siriproxy"  folder. NOT the one where your plugin folder is !!

just copy the example line and make one with    Test
if the ./plugins/siriproxy-test   path doesnt work, use     /Users/xxx/SiriProxy/plugins/siriproxy-test

now go back to your plugin/siriproxy-test/lib folder and
rename your .rb file to siriproxy-test.rb
open it
replace class siriproxy::plugin::Example    with   plugin::Test
save

that should do it.

have fun messing around :-)

**Comment by gotnull** [comment]
Whoah, all of that just to update a plugin? Horrible. lol.

Will give it a shot, thanks.

**Comment by muhkuh0815** [comment]
i wouldnt change the rb files in the /.rvm/ folder, not sure but dont they get overwritten when you do an siriproxy update ?

and no, just edit the path in the config.yml    OR  make your own plugin

**Comment by gotnull** [comment]
Yeah, I think I'll just create my own plugin and play around with that.

**Comment by gotnull** [comment]
@muhkuh0815 Thanks for the help with installing the Test plugin, however I'm getting the following:

I've tried both:
./plugins/siriproxy-remote, and
/home/fulvio/Projects/SiriProxy/plugins/siriproxy-remote

This is the error if I have the following in my: `~/.siriproxy/config.yml`

`/home/fulvio/Projects/SiriProxy/plugins/siriproxy-remote`

=== Bundling ===
Updating git://github.com/chendo/cora.git
Fetching source index for http://rubygems.org/
Could not find gem 'siriproxy-remote (>= 0) ruby' in source at `/home/fulvio/Projects/SiriProxy/plugins/siriproxy-remote`.
Source does not contain any versions of 'siriproxy-remote (>= 0) ruby'

This is what happens if I have `./plugins/siriproxy-remote`

=== Performing Rake Install ===
siriproxy 0.3.0 built to pkg/siriproxy-0.3.0.gem
siriproxy (0.3.0) installed
=== Bundling ===
Updating git://github.com/chendo/cora.git
The path `/home/fulvio/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/plugins/siriproxy-remote` does not exist.
=== Cleaning Up ===
=== SUCCESS ===

I've also tried this and it doesn't work either:

fulvio@fulvio-Ubuntu:~/Projects/SiriProxy$ rvmsudo siriproxy bundle
Updating git://github.com/chendo/cora.git
The path `/home/fulvio/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/plugins/siriproxy-remote` does not exist.
fulvio@fulvio-Ubuntu:~/Projects/SiriProxy$ 

Any ideas what I'm doing wrong?

**Comment by muhkuh0815** [comment]
hmmm ...
 with "/home/fulvio/Projects/SiriProxy/plugins/siriproxy-remote"  he at least finds the right folder.

i would check all the files in the siriproxy-remote folder + config.yml.

have you renamed and edited the siriproxy-remote.gemspec ?
have you "class SiriProxy::Plugin::Remote < SiriProxy::Plugin" in your siriproxy-remote.rb file ?
have you -name: "Remote" in your config.yml ?
is the Gemfile and Rakefile present in you plugin folder ?

i have 7 plugins running with this method. maybe try to move your plugin to the /.rvm/gems/ folder and try it there

**Comment by gotnull** [comment]
@muhkuh0815 I am using the following plugin:

`https://github.com/toddtreece/siriproxy-arduino`

When I hold the HOME button to initiate Siri I get the following error about 'scrapi' not being loaded.

I installed 'scrapi' by executing the following command:

`gem install scrapi` 

It installed correctly so I'm not sure why it's complaining that it can't be loaded:

fulvio@fulvio-virtual-machine:~/Projects/SiriProxy$ rvmsudo siriproxy server
Starting SiriProxy on port 443..
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x87e068c @signature=3, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x87e05b0>, @zip_stream=#Zlib::Deflate:0x87e059c, @consumed_ace=false, @name="iPhone", @ssled=false>
/home/fulvio/Projects/SiriProxy/plugins/siriproxy-arduino/lib/siriproxy-arduino.rb:7:in `require': cannot load such file -- scrapi (LoadError)`

**Comment by gotnull** [comment]
Fixed this by adding the required gems to the .gemspec file for the plugin.

**Comment by JBX028** [comment]
Indeed it's ok. Thanks!
