### ISSUE TITLE
Starting SiriProxy on port 80..

### ISSUE THREAD

**Issue by Bubelbub** [plamoni/SiriProxy#238]
Hello "Issues-Community",

is there a possibility to have siriproxy on port 80?
Or another Port?

I think if a "Public" SiriProxy Server can use Ports vom 1000 to 2000 and on each port, there are extra connections.
Then the Public-SiriProxy-Ports are not so full == No Lags and a functionally SiriProxy-Public Server.

I hope there is a solution.

kind regards
Bubelbub

**Comment by plamoni** [comment]
While I still recommend against public SiriProxy servers for privacy
and security reasons, you can run SiriProxy on an alternate port using
the "-p" flag (e.g. "siriproxy server -p 2000"). I do this at home to
avoid running SiriProxy as root. The trick is to get the phone to talk
to that port. I use iptables PREROUTING rules to redirect traffic to
TCP/2000 that would otherwise go to TCP/443. But that won't load
balance. I'm not sure why you would want to run multiple copies at
once anyway.

-Pete

Sent from my iPhone

On Jan 1, 2012, at 10:17 AM, Bubelbub
reply@reply.github.com
wrote:

**Comment by Bubelbub** [comment]
Ou Plamoni personally ^^

Yes, you´ve right.
With iptables you can do this.

But i want a "Public ProxyServer".
Because this, i want more "copies" at once way.

You know, per Port, one Server.
But this Server can´t hold 100+ Users.
Because this, i want use more Ports = More Servers.

But thank you for your Answer.

**Comment by plamoni** [comment]
Again, I cant support any public servers for security and privacy
reasons. But I really don't see why you couldn't handle hundreds of
users on one copy of the server.

But scalability is a challenge that you generally need a solid
networking background to tackle.

-Pete

Sent from my iPhone

On Jan 1, 2012, at 10:54 AM, Bubelbub
reply@reply.github.com
wrote:

**Comment by Bubelbub** [comment]
Yes, i understand the Problematic.

I´m Developer and no Server Specialist.
Because this, i only start the Server.
IPTables or so i dont configure for SiriProxy.

=]
