### ISSUE TITLE
Unable to Resolve Server Address

### ISSUE THREAD

**Issue by enwave** [plamoni/SiriProxy#24]
/Library/Ruby/Gems/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:714:in `connect_server': unable to resolve server address (EventMachine::ConnectionError)
    from /Library/Ruby/Gems/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:714:in`bind_connect'
    from /Library/Ruby/Gems/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:692:in `connect'
    from ./siriProxy.rb:214:in`ssl_handshake_completed'
    from /Library/Ruby/Gems/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run_machine'
    from /Library/Ruby/Gems/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in`run'
    from ./siriProxy.rb:245:in `initialize'
    from start.rb:16:in`new'
    from start.rb:16

Trying to run SiriProxy through dd-wrt dnsmasq options so I don't have to wifi share an ethernet connection. Added:
address=/guzzoni.apple.com/192.168.1.142 

to the dnsmasq configuration in dd-wrt and it is clearing redirecting guzzoni traffic somewhere. What concerns me is the ssl_handshake_completed errer in siriProxy.rb, Does that mean I made a mistake creating certificates or placing certs somewhere? Anyone have any ideas?

**Comment by plamoni** [comment]
The error is coming when you try to connect to guzzoni.apple.com. Make sure the server that's running the proxy knows the REAL address for guzzoni.apple.com. This means when you do a "ping guzzoni.apple.com" on your dd-wrt box, you should get an address back that's in the 17.X.X.X subnet (not in your local subnet).

If this fixes it, close the issue. Thanks! :-)

**Comment by netpro2k** [comment]
Like  plamoni said you need to make sure the machine running the proxy is not hitting the dnsmasq. If you are using dhcp connecting to the same router it likely is. Perhaps try setting your computer's dns to a different dns like 8.8.8.8 (google's public dns)

**Comment by enwave** [comment]
I can't believe I didn't think of that myself! Sometimes bumping heads on an issue makes all the difference. Thanks guys, changing DNS servers did the trick. It was resolving guzzoni.apple.com right back to my 192.168 local address. I'll close the issue!

**Comment by venom420x** [comment]
i know this issue is closed but i just wanted to thank all three of you i've been trying to get this running for a week now and i've been doing it through ddwrt like emwave after the thousands of attempts on doing this i thought it couldn't be done through the routers dnsmasq but this helped so much now its finally up and running THANK YOU

**Comment by charlesfracchia** [comment]
I thought I would add my experience here. I set up SiriProxy in a Ubuntu 12.04 VM and found that this version has a default entry for resolving. In /etc/resolv.conf there is "nameserver 127.0.0.1" entry that will cause an infinite loop for guzzoni.apple.com. By changing that line to "nameserver 8.8.8.8" you will break out of that loop. Please bear in mind that this is a temporary solution because the moment you restart the connection or dnsmasq, the file is returned to its original state of looping back. This is the blog post that lead me to diagnosing the problem: http://www.stgraber.org/2012/02/24/dns-in-ubuntu-12-04

In order to make the above solution permanent, it would seem that adding "nameserver 8.8.8.8" to /etc/resolvconf/resolv.conf.d/head does the trick. I found info about this fix here: http://guy.vsbnet.be/content/fighting-dns-resolving-ubuntu-1204-server
