### ISSUE TITLE
Siri doesn't understand "Test Siri proxy"

### ISSUE THREAD

**Issue by arketec** [plamoni/SiriProxy#279]
Hello everyone,

This is my first attempt at Ubuntu, so I don't doubt I am screwing up, but as far as I can tell I have done everything correctly. I followed all directions and did not run into any issues setting the server up. I changed installed the ca.pem to my 4S and changed the DNS to the server ip but Siri does not understand. My network connections are bridged and the iPhone can connect to the internet through the proxy DNS server (for instance, Safari works.) If the phone wasn't connecting through the server, none of the Internet would work through the wifi, but everything does but Siri. Any help would be much appriciated, I've been at this all night.

**Comment by ghost** [comment]
Is your SiriProxy giving you any output to your terminal while you are trying to use ur 4S?

**Comment by arketec** [comment]
nothing, it just stays at "Starting SiriProxy on port 443.."

**Comment by arketec** [comment]
I just attempted to ping the proxy server and the apple server from my 4S. I received a reply from the proxy server but not the apple server. I really do not know what to do from here.

**Comment by edsonaj** [comment]
Try to see if the dnsmasq configs are right.

**Comment by MUDKENAO** [comment]
I had the same problem. After I added my server ip to iphone' wifi dns, problem solved. Hope this tip can help you.

**Comment by arketec** [comment]
Yeah tried that originally. I ended up just starting from a fresh Ubuntu install, only now I'm having issues with my land based Internet, but that's separate entirely

**Comment by djrobx** [comment]
I'm having the same problem.   In my case, I can see tons of messages flying on SiriProxy, but it seems like the phone is also trying via 3G or a different IP in parallel or something, because Siri still works even if I close SiriProxy!

Update: I figured this out - the machine I was using had resolve.conf pointing at itself, so guzzoni.apple.com was resolving to the localhost.  SiriProxy was talking to itself!    D'oh.  Thats what I get for messing with a linux install that I haven't touched in 2 years.
