### ISSUE TITLE
Opening SiriProxy after a restart

### ISSUE THREAD

**Issue by jmeyerhead** [plamoni/SiriProxy#318]
ok so I got siri proxy up and running, even installed some plug ins. I restarted my computer, opened up terminal typed " cd SiriProxy" got to the siriproxy directory and then used "rvmsudo siriproxy server" and its saying "No such file or directory" ... what am i﻿ doing wrong? .... I checked around for an answer but it seems that most people are getting this before their install and not after.

**Comment by Ponyboy47** [comment]
Yeah ive been getting this error also..to fix it i found that you need to redo the rake install. If you still get the same error then reclone the repository and then try rake install..

**Comment by TobyTech** [comment]
I would just re-install. I have so many theories for this and so many things to try, but it will take a shorter time for me and you to just delete the SiriProxy directory and ~/.siriproxy  directory and re-install.

**Comment by jmeyerhead** [comment]
just found out that putting in these commands:

bash < <(curl -s https://raw.github.com/wayneeseguin/rvm/master/binscripts/rvm-installer)
[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"
echo '[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm" # Load RVM function' >> ~/.bash_profile

followed by a bundle install gets it up and running.

**Comment by davidgeppelt** [comment]
You need to do the whole installation process as root. Login using 'sudo su' > password, then follow the installation instructions but leave out 'sudo' where it says it is required. Because some of the commands require root privilege it is installing half as a normal user, and the others as root. So to prevent this, as I said, log in as root and do the whole installation process. Then when you shut down you computer, or exit the terminal window, all you need to do is open another terminal window, log in as root, cd to the Siri directory, and there you go. Also, while you are logged in as root, there is no reason to do 'rvmsudo siriproxy server'. Since you are root just do 'siriproxy server'.
