### ISSUE TITLE
Config.yml not found

### ISSUE THREAD

**Issue by shanagarwal** [plamoni/SiriProxy#349]
hey guys,

i'm doing a fresh install of siriproxy.
i get this error when i do a rake install.

config.yml not found. copy config.example.yml to config.yml, then modify it.

where is config.yml? and what am i suppose to modify in it?

**Comment by shanagarwal** [comment]
@plamoni

**Comment by shanagarwal** [comment]
@westbaer

**Comment by jendas** [comment]
I have same issue. Does anybody know the solution to this problem?

**Comment by plamoni** [comment]
~/.siriproxy/ three is an example config in there.

**Comment by jendas** [comment]
I find the soluton for this problem. After commands clone git://github.com/plamoni/SiriProxy.git and cd SiriProxy, you must create new folder in home folder named .siriproxy and copy and rename the config.example.yml there. After that use command: rvm all do bundle install, and right after this command: rvm all do rake install. This steps worked for me.

**Comment by AlexJWayne** [comment]
Just ran into this too.  `rake install` step in the README needs to come after the creation of `~/.siriproxy/config.yml`

**Comment by Margo78** [comment]
Hello my name is Skyzo, i have the same error : 

config.yml not found.

My SiriProxy folder is in my personnal folder (home/XXX/SiriProxy)
inside this i have the two file : config.yml and example.

I have create a folder in my home folder who is calling .siriproxy 
inside this i have the two file : config.yml and example.

I return in the terminal but when i put command :
cd SiriProxy (home/XXX/SiriProxy)
 rake install 

i have error: config.yml not found. copy config.example.yml to config.yml, then modify it.

Do i must modified inside config.yml  ? 

Thank you for your help. Please use simply word i m not english.

**Comment by Deanmv** [comment]
You need to run:

<code>mkdir ~/.siriproxy</code>

<code>cp ~/SiriProxy/config.example.yml ~/.siriproxy/config.yml</code>

<code>cd ~/SiriProxy</code>

<code>rake Install</code>

Where SiriProxy is the folder you install the download to. (Watch out for the dot and non dot on the same folders)

**Comment by Margo78** [comment]
Hello, thank you very much for your response.
I m on this project since few day and i solve many probleme.... :)

Ok i have do that and it's work.... i havec install all api keys, gen 
certicifacte etc... but i have a last error concerning the wordnik 
plugins when i start siriserver :

$ ./siriServer.py --port 443
CRITICAL load_plugins Failed loading plugin due to missing module: 
'Wordnik library not found. Please install wordnik library! e.g. sudo 
easy_install wordnik'
INFOStarting Server
INFO **init** Listening on port 443
INFOCaught shutdown, closing server

I have : easy_install wordnik
go to //developer.wordnik.com/libraries"]Wordnik Developer
go to //github.com/wordnik/wordnik-python"]wordnik/wordnik-python Â· GitHub

I have install all package nothing to do ! the error appear again.

If you can help me a last time... Thank you

Skyzo

**Comment by Deanmv** [comment]
To start the server it should be:

<code>rvmsudo siriproxy server</code>

I've neve seen that error before so not sure what it is. 

Or try loading the siriproxy with just the example plugin as that output seems to be the plugin that it is failing to load.
