### ISSUE TITLE
RVM does nothing!

### ISSUE THREAD

**Issue by davidgeppelt** [plamoni/SiriProxy#378]
When I try to install rake or bundler with rvmsudo, it just sits there. When I try to start the server with rvmsudo it just sits there. What is wrong with RVM?

**Comment by JoshuaCarroll** [comment]
I've also been having some problems with rvmsudo. I've been having to do this:

sudo -s
rvm 2.9.3 do X

Where X is the command you want to run ("rake install" or "siriproxy server"). 

Works, but its a pain since I can't really script it this way. 

---

Joshua Carroll
about.me/joshuacarroll

Sent from my mobile device
(Please excuse any errors.)

**Comment by Deanmv** [comment]
Should be 1.9.3 and not 2.9.3 I think?

**Comment by JoshuaCarroll** [comment]
Typo. You are correct. 

---

Joshua Carroll
about.me/joshuacarroll

Sent from my mobile device
(Please excuse any errors.)

**Comment by davidgeppelt** [comment]
Okay, worked fine with everything. But when I come to start siriproxy it gives me:

sudo -s
rvm 1.9.3 do siriproxy server

/home/usr/.rvm/scripts/set: line 13: exec: siriproxy: not found

Any ideas? I have been looking though Google, but no solution found yet.

**Comment by davidgeppelt** [comment]
Also, I thought you did want to do a rake install as root. Or am I wrong?

**Comment by davidgeppelt** [comment]
Alright, I started fresh and it works now. When in doubt, start over.
