### ISSUE TITLE
cannot start the server! sudo: siriproxy:command not found

### ISSUE THREAD

**Issue by ghost** [plamoni/SiriProxy#381]
I have tried starting over many times and got past the rake install problem and that worked. but whenever i try to run rvmsudo siriproxy server, it gives me this:

key@ubuntu:~/SiriProxy$ rvmsudo siriproxy server
sudo: siriproxy: command not found
key@ubuntu:~/SiriProxy$ 

I can't get past this, and obviously siriproxy should be a recognized command considering it worked for siriproxy gencerts and siriproxy bundle. Any help on this problem would be greatly appreciated. but if i start it without superuser permissions, it actually starts on port 443 but then stops because i didn't run it with superuser permission of course. so whats wrong with rvmsudo? i followed this tut btw...
https://gist.github.com/1428474

Thanks in advance for any help!

**Comment by davidgeppelt** [comment]
I had the same issue. I have not been able to find where the issue is, but the solution I found, thanks do another post, if you execute as root (sudo -s) with the command "rvm 1.9.3 do X" (X = rake install/ siriproxy bundle/ siriproxy server) it should execute - it did for me. I know plamoni says not to be in root, but honestly I know of no good reason why this could be an issue. If it does not work, try going back and rake installing and bundling with the commands I gave above. Let me know how it works out.

**Comment by ghost** [comment]
Didn't work :( shows
/bin/bash rvm command not found! But if i start the server with rvmsudo bundle exec siriproxy server it starts! But alas none of my devices show up there! Can't connect to SiriProxy it doesnt say anything after starting server on port 443. Have certificates and everything!

EDIT: actually my ipod touch 4 connects with cert but my iphone 5 cant connect, which is what i want to connect so the keys can be input (using westbaers's fork)

**Comment by davidgeppelt** [comment]
I mean, assuming you followed all of the steps correctly, besides the alternative commands I told you, I've got nothing for you. Might try starting from scratch. But it looks like you missed something(s). Like not adding RVM into your Bash profile.

**Comment by ghost** [comment]
thanks
