### ISSUE TITLE
iOS 6.1 Beta 4

### ISSUE THREAD

**Issue by joshluongo** [plamoni/SiriProxy#406]
_I have modified this to remove information protected by Apple's developer NDA, please do not disclose information about pre-release software from Apple -- Pete_

**Comment by plamoni** [comment]
Please refrain from discussing pre-release features or changes because they
are covered by the iOS developer NDA. If they change something like that in
a public release, I will update the docs.

Thanks,

-Pete

On Jan 11, 2013, at 2:59 AM, Josh Luongo notifications@github.com wrote:

With my iPhone 5 running iOS6.1b4 i was unable to use siri proxy, it turns
out that Apple have changed the Siri server it is now at: daisy.apple.com

You will also need to change your dnsmasq settings
address=/daisy.apple.com/

And you need to change the domain in the scripts/gen_certs.sh file.

—
Reply to this email directly or view it on
GitHubhttps://github.com/plamoni/SiriProxy/issues/406.
