### ISSUE TITLE
Do i need dnsmasq?

### ISSUE THREAD

**Issue by NeMeSiStm** [plamoni/SiriProxy#449]
Do i need dnsmasq if i have already a DNS and DHCP server running?

thats my question. in my eyes dnsmasq is delivering a DNS and a DHCP server. but i have already both up and running on my network.

**Comment by plamoni** [comment]
Nope. You're welcome to use what you have set up assuming you know how to override a DNS entry for your local network. You just need to override the DNS for `guzzoni.apple.com` to point to your SiriProxy server.

Also, I suggest you use the dev branch (`siriproxy update --branch dev`), as it will default to use Google's DNS servers to query the real guzzoni address (otherwise you have to override the override for your SiriProxy box and that can be messy).

dnsmasq just provides a simple solution to the DNS override requirement, but if you can do without, you're more than welcome to do so.

**Comment by NeMeSiStm** [comment]
thanks for the fast answer. siriproxy up an working! great work!
