### ISSUE TITLE
Is it possible to reset config variable

### ISSUE THREAD

**Issue by Dageek4590** [plamoni/SiriProxy#521]
in the rb file where I initialize the config. I set a couple variable that pull from the config.yml file.

Is it possible to write a listen command that resets one of those variable to something else and makes it available to every listen command in th rb file?

maybe not an issue. but where should i post just general questions?

**Comment by elvisimprsntr** [comment]
This is not a open forum for how to program in Ruby, I suggest you do some basic Ruby programming reading.   Only after you have exhausted all you efforts post a question on. Ruby specific forum, ie stackoverflow.  

Regardless, the initialization section of your Ruby plugin will execute for every new Siri connection and in some cases during launch of SiriProxy.    In your case I suggestion you read up on different variable types and his to declare, initialize, and modify them.  

Since this is not a SiriProxy specific question or problem I'm closing.
