### ISSUE TITLE
Problem with rake install

### ISSUE THREAD

**Issue by theolsen** [plamoni/SiriProxy#530]
Hi all, I've been trying to get Siriproxy up and running for about a week now. I seem to be having problems with rake install.

I'm a novice so I am probably getting what I deserve!

Here's what I get: 
hoglets-imac:SiriProxy daveolsen$ gem install /Users/daveolsen/SiriProxy/pkg/siriproxy-0.5.4.gem
Fetching: CFPropertyList-2.1.2.gem (100%)
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied - /Users/daveolsen/.rvm/gems/ruby-1.9.3-p429@SiriProxy/cache/CFPropertyList-2.1.2.gem
hoglets-imac:SiriProxy daveolsen$ 

I'm happy to set up teamviewer if somebody would like to have a poke.

Thanks,

Dave.

**Comment by elvisimprsntr** [comment]
You really taking the hard road...
1. Is there some particular reason you need to run SiriProxy natively on Mac OSX?  Because you will be a minority of the user population which you are less likely to be successful or receive support. Since you have admitted you are new, I recommend you consider installing a virtual machine like virtualbox.org and install Ubuntu Linux.  Once you have RVM, Ruby, and SiriProxy running, and still insist on running natively on Mac OSX you will have to look for other sources and forums for advice. 

Elvis

**Comment by theolsen** [comment]
Thanks elvisimprsntr, that's probably just the push I needed...installing virtualbox now. Wish me luck :-)

**Comment by elvisimprsntr** [comment]
Remember to use a bridged Ethernet controller.   That's the only tweak from the virtualbox defaults.

**Comment by theolsen** [comment]
Thanks man. Appreciate the help.
