### ISSUE TITLE
How do I hijack the speech stream and send it to playback directly?

### ISSUE THREAD

**Issue by fluentfuture** [plamoni/SiriProxy#552]
Hi, I'm trying to turn iPhone into a remote microphone and then playback the voice with a raspberry pi downstairs.

The UI of Siri (press the home button and start talking, without need to unlock the phone and look for app) seems more convenient than any other solution I could find (I tried RemoteMic on iPhone, Wo Mic on Android).

I'm thinking to:
- install SiriProxy on raspberry pi.
- configure dns so iPhone Siri talks to it.
- Configure or modify SiriProxy code to hijack the input voice and play it back directly.

So I was looking in the source code hoping to find a place to hajack the whole guzzoni process. But I think I might need some help to find the right code location. There are iPhone.rb and Guzzoni.rb, both extending Connection. But Connection.rb seems to be designed to consume data coming back from Guzzoni, not voice stream coming from iPhone. Yes?

Where is the code that takes stream from iPhone and sends it to Guzzoni? 

I guess I'm not even sure if this is possible with how Siri works?

Thank you for the great work and any hint you can give! And apology if this was asked before.

**Comment by elvisimprsntr** [comment]
Seems like it would be a lot easier to run a speech synthesizer on the RPi and pass the converted text rather than try to process the compressed voice packets directly.  Wouldn't be in your own voice but I'm not sure what the quality of the compressed voice packets are. 

In either case, this is not really a issue for SiriProxy to track.  You will need to modify the source code on your own. I suggest you post your question on a number of forums which specialize in Ruby.   Try increasing the SiriProxy log level to help pinpoint where you will need to modify the code.

**Comment by fluentfuture** [comment]
Thank you for the quick reply!

I didn't realize the issue of sound quality of the compressed voice. So perhaps it's a no-go then, unless I can hack the Siri client on iPhone.

(Yes. Wife said if it's not her voice, she'd not use it)

**Comment by elvisimprsntr** [comment]
Here is a thread from someone who tried before

https://github.com/plamoni/SiriProxy/issues/209
