### ISSUE TITLE
Gencerts Exec format error

### ISSUE THREAD

**Issue by hokesen** [plamoni/SiriProxy#558]
Whenever I try to do 

C:\Users\Simon\Desktop>siriproxy gencerts

I get this error message.

C:/Ruby193/lib/ruby/gems/1.9.1/gems/siriproxy-0.5.4/lib/siriproxy/command_line.rb:114:in ``': Exec format error 
- C:/Ruby193/lib/ruby/gems/1.9.1/gems/siriproxy-0.5.4/lib/siriproxy/../../scripts/gen_certs.sh "C:/Ruby193/lib/ruby/gems/1.9.1/gems/siriproxy-0.5.4/lib/siriproxy/../.." "" (Errno::ENOEXEC)
      from C:/Ruby193/lib/ruby/gems/1.9.1/gems/siriproxy-0.5.4/lib/siriproxy/command_line.rb:114:in `gen_certs'
      from C:/Ruby193/lib/ruby/gems/1.9.1/gems/siriproxy-0.5.4/lib/siriproxy/command_line.rb:40:in`initialize'
      from C:/Ruby193/lib/ruby/gems/1.9.1/gems/siriproxy-0.5.4/bin/siriproxy:6:in `new'
      from C:/Ruby193/lib/ruby/gems/1.9.1/gems/siriproxy-0.5.4/bin/siriproxy:6:in`<top (required)>'
      from C:/Ruby193/bin/siriproxy:19:in `load'
      from C:/Ruby193/bin/siriproxy:19:in`<main>'

C:\Users\Simon\Desktop>

This is the line that is causing the error 

puts `#{command} "#{sp_root}" "#{ca_name}"`

Am I doing something wrong?
I am running Windows 8

**Comment by elvisimprsntr** [comment]
My guess is you are trying to run a Linux native version of siriproxy on Windows.  You have several options:
1. The hard road... Find a Windows port of siriproxy and installation instructions, which you will likely be running an outdated version of Ruby.   Also, you are less likely to receive much if any support (certainly from anyone here) since you would be a minority of the siriproxy user community.  
2. Still a hard road...   Dual boot your machine between Windows and Linux.  It's not fun and can cause problems with the Windows boot partition if you configure it incorrectly.   Might even require you to perform a clean install of Windows.  Not recommended for anyone not already familiar with dual boot.  
3. Slightly easier... Repurpose an old machine specifically for Linux, buy a new machine or a $35 Raspberry Pi.  
4. No cost and easiest way is to install an open source (free) VM from www.virtualbox.org, Install Ubuntu (Server or Desktop), then install RVM, Ruby, and SiriProxy.  The default options for Virtualbox are fine, except select a bridged Ethernet adapter to ensure the Linux Guest OS is assigned a unique IP address, separate from the Windows Host.
