### ISSUE TITLE
zlib(finalizer): the﻿ stream was freed prematurely.

### ISSUE THREAD

**Issue by venom420x** [plamoni/SiriProxy#56]
i get this everytime i start start.rb

i so 
rvmsudo ruby start.rb
and the server starts its recieves my speech packets

i say test Siri Proxy and then it give me the zlib(finalizer): the﻿ stream was freed prematurely.

**Comment by venom420x** [comment]
any help greatly appreciated

**Comment by venom420x** [comment]
just to be a little more descriptive

/Users/VeNoM/.rvm/gems/ruby-1.9.3-p0/gems/eventmachine-0.12.10/lib/eventmachine.rb:714:in `connect_server': unable to resolve server address (EventMachine::ConnectionError)
    from /Users/VeNoM/.rvm/gems/ruby-1.9.3-p0/gems/eventmachine-0.12.10/lib/eventmachine.rb:714:in`bind_connect'
    from /Users/VeNoM/.rvm/gems/ruby-1.9.3-p0/gems/eventmachine-0.12.10/lib/eventmachine.rb:692:in `connect'
    from /Users/VeNoM/Desktop/Siri/siri_proxy/connection/iphone.rb:20:in`ssl_handshake_completed'
    from /Users/VeNoM/.rvm/gems/ruby-1.9.3-p0/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run_machine'
    from /Users/VeNoM/.rvm/gems/ruby-1.9.3-p0/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in`run'
    from /Users/VeNoM/Desktop/Siri/siri_proxy.rb:16:in `initialize'
    from start.rb:22:in`new'
    from start.rb:22:in `<main>'
zlib(finalizer): the stream was freed prematurely.

**Comment by plamoni** [comment]
This error indicates that the server is unable to resolve the IP address for guzzoni.apple.com. I would check your DNS settings on your server. Make sure that pinging guzzoni.apple.com gives you an IP (they block ICMP, so don't worry if all your pings are dropped -- just make sure it resolves into a 17.0.0.0/8 address).

**Comment by venom420x** [comment]
thank you for the response. i pinged and got a address for my mac not a 17 address. heres my console.

matts-imac:Siri VeNoM$ ping guzzoni.apple.com
PING guzzoni.apple.com (192.168.1.134): 56 data bytes
64 bytes from 192.168.1.134: icmp_seq=0 ttl=64 time=0.054 ms
64 bytes from 192.168.1.134: icmp_seq=1 ttl=64 time=0.066 ms
64 bytes from 192.168.1.134: icmp_seq=2 ttl=64 time=0.056 ms
64 bytes from 192.168.1.134: icmp_seq=3 ttl=64 time=0.065 ms

im sure you know it just keeps going from here

**Comment by plamoni** [comment]
Your DNS is set up improperly. 

Your server needs access to the REAL guzzoni.apple.com servers. Meaning you cannot have your server pointed to the poisoned DNS entry, otherwise it just creates an infinite loop. This is not an issue with the application, but an issue with getting it set up.

**Comment by venom420x** [comment]
in the guide it tells us to point the dns server to our macs ip. which address should i put in 

this is what i have

address=/guzzoni.apple.com/192.168.1.134

that is my macs ip address. my router has dnsmasq installed on it should i use that instead?

**Comment by iPodHacks142** [comment]
Im having the same problem, please tell me how to fix it

**Comment by nilsi** [comment]
Seems like I have the same issue, someone got a clue?

**Comment by shaiss** [comment]
same issue here, any updates?

**Comment by lhilton** [comment]
As stated, the issue is that your SiriProxy server is using it's own DNSMasq to resolve names. SiriProxy itself needs to have normal access to **guzzoni.apple.com**. This is probably because you are running something like Ubuntu 12.04 or 12.10, where they are now running DNS through a newer process.

The end result is that you need to be using a public nameserver (like 8.8.8.8 or your ISP's provided values) on the server. If you check /etc/resolve.conf I would be it is giving you some mumbo jumbo about resolvconf and DO NOT MAKE CHANGES and stuff. If so, the shortest path out is to take all that out of the loop.

**Warning, you might break stuff**

What I do is run:

**sudo rm /etc/resolve.conf**

Then I run:

**sudo vi /etc/resolve.conf**

I insert this:

**nameserver 208.67.222.222**  <- substitute with whatever DNS server you want

Then I run this:

**sudo service networking restart**

I think that will get where you want to be.
