### ISSUE TITLE
DNS server issue when restarting server

### ISSUE THREAD

**Issue by gadgetchnnel** [plamoni/SiriProxy#560]
I am using SiriProxy on OS X 10.8.4 and I am using the -d option to start the DNS server. This works fine the first time I run it. However, if I terminate the server and then try to start it again, I get the following:

> [Info - Server] Starting SiriProxy on 0.0.0.0:443...
> [Info - Server] DNS server is not running yet, waiting 1 second...
> [Info - Server] DNS server is not running yet, waiting 2 second...
> [Info - Server] DNS server is not running yet, waiting 4 seconds...

...and so on, until I terminate it.

After rebooting the Mac, SiriProxy will start successfully again until the server is terminated again.

Am I doing something wrong, is there a way to terminate the server gracefully and stopping the DNS server?

**Comment by elvisimprsntr** [comment]
1. You are a minority of the SiriProxy user community when running natively on OSX, which you are less likely to be successful or receive support. Is there a particular reason you need to run SiriProxy natively on OSX vs. on a VM running Ubuntu like 99.999% of the community?
2. Sounds like RubyDNS cannot start the DNS server due to a dependency on some other daemon which crashed when you terminated SiriProxy. You will have to take that matter up with the RubyDNS repo/gem owner.   If you must run natively on OSX, I recommend you install and configure DNSMASQ and not use the -d option when launching SiriProxy.
