### ISSUE TITLE
Siri Logitech Smart Control

### ISSUE THREAD

**Issue by hotrod225** [plamoni/SiriProxy#563]
Hey guys,

Im a complete newbie when comes to the siri proxy and plugin coding, but I was wondering if someone can give me some guidance....... I use Logitech's Smart Control for my entertainment center and I know that smart phones communicate with the hub through wifi or internet. Any suggestions on how to start writing a plugin to control it through Siri?

**Comment by tdubbz** [comment]
I've been waiting for this as well.  In fact, I pre-ordered the Smart Control to replace my existing Harmony remote since I was hoping it would be an easy REST API to replay from the iphone application.  Unfortunately, after spending some time looking at the traffic, it's actually XMPP and there's no public documentation provided by Logitech.  The app logs into myharmony.com for an authorization key, and then uses that against the hub which makes it eve more complicated.  Do a quick google search for XMPP and Harmony and you'll find many others attempting to figure this out. 

This project looks promising, but I wasn't successful in my testing against my Smart Control: 
https://github.com/jterrace/pyharmony

**Comment by elvisimprsntr** [comment]
That's the problem with a closed proprietary device with no documented public API, which Logitech will never publish.  Someone will have to reverse engineer the API to write a SiriProxy plugin for voice control.  

Since this is not an issue with SiriProxy itself, I'm going to close this ticket.  If you ever do create a working plugin feel free to add it to the plugins Wiki page.
