### ISSUE TITLE
Siri Authentification Bypass

### ISSUE THREAD

**Issue by moieza** [plamoni/SiriProxy#569]
Hello,
a new tweak to bypass authentication is out, works perfectly ! 
1. install Ac!d or Spire
2. install Siri Authentication Bypass
3. IP: Https://guzzoni.apple.com (optional) 

Repo : http://Get-Siri.myrepospace.com/

How is that possible? oO

**Comment by plamoni** [comment]
I would imagine it's possible because they jailbreak. After that, it might be possible to do some sort of protocol downgrade or something similar. You can do pretty much anything on a jailbroken phone.

SiriProxy doesn't require a jailbreak to work. At least it doesn't when it's working. iOS7 seems to have killed SiriProxy for now. Not sure if/when it will be working again for non-jailbroken devices.
