### ISSUE TITLE
SiriProxy Error

### ISSUE THREAD

**Issue by KirmaanA** [plamoni/SiriProxy#98]
Whenever I Try To Use "siriproxy bundle" or "siriproxy gencerts" I get this error

Kirmaan-Aboobakers-MacBook-Air:~ Kirmaan$ siriproxy gencerts
-bash: siriproxy: command not found

Thanks

**Comment by Taruga** [comment]
Use: git clone https://github.com/plamoni/SiriProxy.git

**Comment by benjaminwood** [comment]
I too am having this issue. Had things running fine before the recent gem switch. I've got the project cloned in my user home folder. Rake install returns "siriproxy 0.0.1 built to pkg/siriproxy-0.0.1.gem" & "siriproxy (0.0.1) installed" and is indeed in the pkg folder. Can't get siriproxy to be recognized in terminal though...

Any help would be appreciated. Thanks!!

I LOVE siriproxy!

**Comment by flash66** [comment]
bash-3.2$ cd siriproxy/pkg
bash-3.2$ rvmsudo gem install siriproxy

You have to install the gem file for Siri. Plamoni missed this step in the read me. 
Then you can execute siriproxy

**Comment by benjaminwood** [comment]
Hi flash66, thanks for your reply. I tried your suggestion and it said that it installed successfully, but it's still acting like its not installed: siriproxy: command not found.

Doesn't "rake install" build the gem and then install it? Did plamoni miss the step? Or am I experiencing another problem?

Thanks, I'm still running the previous version of siriproxy and am having fun learning & learning a lot. Appreciate the help!

**Comment by flash66** [comment]
Hi Ben,  I have to say, I've ran into a few annoying problems installing this on my system. To first answer your question, try running anything "siriproxy" with 'rvmsudo'.  ''rake install' does not install the the Siri gem. although it looks like it does. After manually installing the gem from /pkg by:
 'rvmsudo gem install siriproxy' 
 Your command 'siriproxy bundle' should work but may have errors. To fix this just use
 'rvmsudo siriproxy bundle'. 
 The was also an issue installing the gems, as some ruby configuring was going on. if I remember correctly, you might get this:

 ""ERROR: There has been an error while running configure"" 
halting the process. Running this command with clang fixed the ruby issue.
  'rvm install 1.9.3 --with-gcc=clang' 

After that, just a few syntax errors in my config.yml for my plex plugin , and I was set. Make sure the config.example.yml is renamed to config.yml and put into the .siriproxy folder inside your siriproxy root folder. Don't forget to bundle!

   The creation of the hidden .siriproxy folder step was the beginning of my trouble. It kept saying it already existed but it was invisible so.......  Also the "siryproxy gencerts" did not work for me. a path couldn't be found so creation was a failure without the .crt file to rename and move.

 I used the previous cert from my old siriproxy folder with success. You can still generate one the old way.   There are a couple of additions that should be in the read me file, but with persistence you'll figure it out. Hope this helps! -TS

**Comment by flash66** [comment]
https://github.com/plamoni/SiriProxy/wiki/Common-Errors-and-Solutions

**Comment by plamoni** [comment]
Can someone confirm that you must install the gem separately from the rake install? I do not think this is necessary, but others do. 

Also, rake install should not be run as root.

**Comment by benjaminwood** [comment]
Hey guys, thanks for the help! After some more trial and error, I came to this conclusion:

1.
Running "Rake install" returns
siriproxy 0.0.1 built to pkg/siriproxy-0.0.1.gem
siriproxy (0.0.1) installed

It did generate "pkg/siriproxy-0.0.1.gem"
As far as I could tell it didn't install siriproxy.
It did create the folder "/Users/benjamin/.rvm/gems/ruby-1.9.3-p0/gems/siriproxy-0.0.1" but didn't populate it.
It did not put siriproxy in "/Users/benjamin/.rvm/gems/ruby-1.9.3-p0/bin"

As suggested I tried running "'rvmsudo gem install siriproxy" from the pkg folder. For me, it gave the same results as rake install which is that it says it installed, but it didn't!

2.
I ended up manually moving the needed files from my cloned siriproxy folder to "/Users/benjamin/.rvm/gems/ruby-1.9.3-p0/gems/siriproxy-0.0.1" and "/Users/benjamin/.rvm/gems/ruby-1.9.3-p0/bin"

3.
After this I could run "Siriproxy Gencerts" but it came with errors.

Generated ~/.siriproxy/server.passless.key
Generated ~/.siriproxy/ca.pem
Did not generate ~/.siriproxy/server.passless.crt

I ended up using my certificate files from my original siriproxy install that were created manually.

4.
"siriproxy bundle" returned a permissions error. "rvmsudo siriproxy bundle" seemed to do the trick.

After all that… "rvmsudo siriproxy server" and..

Siriproxy is up and running!

**Comment by flash66** [comment]
That's great Ben. As I said rake install builds the gem but installation needs manual intervention. 
So I guess it's confirmed. The gencert also needs a bit of work. Seems the problem is primarily incorrect paths. 
Glad to hear you have it up and running.

**Comment by flash66** [comment]
By the way, the gem should have been populated with rake to /pkg not /bin.

**Comment by benjaminwood** [comment]
Yeah, this confirms that at least for some rake install doesn't install the gem. I have a couple of friends that are experiencing that same issue, so I know it's not just us.

The gem was populated to /pkg but since I couldn't get it to install I manually moved the entire contents of the siriproxy folder to "Users/benjamin/.rvm/gems/ruby-1.9.3-p0/gems/siriproxy-0.0.1". I also had to move the "siriproxy" (no extension) file form /bin into place at "/Users/benjamin/.rvm/gems/ruby-1.9.3-p0/bin".

Thanks again flash! I greatly appreciate the help. 

Thanks plamoni for all your hard work! Siriproxy is a brilliant idea!

**Comment by delrio1110** [comment]
Hi Guys,
i just want to say thank you for all your help and i have run into alot of issues but you have help me resolve them. my last iss is with cert, im getting the following error.

David-Hernandezs-iMac:~ dhernandez1110$ rvmsudo siriproxy server
Starting SiriProxy on port 443..
Create server for iPhone connection
/Users/dhernandez1110/.rvm/gems/ruby-1.9.3-p0/gems/eventmachine-0.12.10/lib/em/connection.rb:304:in `block in start_tls': Could not find /Users/dhernandez1110/.siriproxy/server.passless.crt for start_tls (EventMachine::FileNotFoundException)

**Comment by flash66** [comment]
server.passless.key server.passless.crt

Make sure these two files are in your Siriproxy folder.

**Comment by delrio1110** [comment]
thanks Flash i have finally got it up and running. how do i stop the siri proxy so that i can make changes.

**Comment by benjaminwood** [comment]
Control c

**Comment by delrio1110** [comment]
im playing around with siri and the plug-in and i was wondering if i just wanted to add some some new text to the siriproxy example where would i make those changes so that siri will say them. sorry but im new at this.

**Comment by flash66** [comment]
Look inside the files and code samples. Play around with them and have some fun. Learning what to do will help you master it. It's just text in the samples. Try changing " Siri Proxy is up and running" to something else.  That will get you started.

**Comment by aurel6710** [comment]
Hello,
I'm stuck at step 5 (siriproxy gencert).
So I go in the pkg directory. And I do "gem install rvmsudo siriproxy-0.0.1.gem". 
But I don't understand what to do after that.
When I call "siriproxy gencert" or "siriproxy-0.0.1 gencert" it doesn't work.

**Comment by flash66** [comment]
Try rvmsudo siriproxy gencert

**Comment by nandor690** [comment]
I cd to /SiriProxy/pkg then I run rvmsudo gem install siriproxy-0.0.1.gem and I get this.....

Successfully installed siriproxy-0.0.1
1 gem installed
Installing ri documentation for siriproxy-0.0.1...
file 'lib' not found
Installing RDoc documentation for siriproxy-0.0.1...
file 'lib' not found

So I thought GREAT its finally installed!!! But when I try to run it "rvmsudo siriproxy server" I get 
-bash: siriproxy: Command not found.

Im new to ruby and I'm not quite sure exactly what benjaminwood was talking about. I get were to paths are but not sure what files/folders to move.

I had no problem getting it running the initial why with start.rb, but I can't use that anymore :-(

any help would be appreciated

-Nandor690

EDIT: Ok I figured out that "for me at least", I had to move /Users/Nandor/SiriProxy/bin/siriproxy > /Users/Nandor/.rvm/rubies/ruby-1.9.3-p0/bin. That allowed me to start using the "siriproxy" in the command line for the gencerts.
I tried to move it to /Users/Nandor/.rvm/gems/ruby-1.9.3-p0/gems/siriproxy-0.0.1but that did nothing for me. Instead of following the path on through the /gems/ directory I had to go through the /rubies/ directory. (Maybe a typo on his part, but not sure)
But I can't figure out where the command_line.rb goes so I can fix this error when running "rvmsudo siriproxy server"

 rvmsudo siriproxy server
/Users/Nandor/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- siriproxy/command_line (LoadError)
    from /Users/Nandor/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from /Users/Nandor/.rvm/rubies/ruby-1.9.3-p0/bin/siriproxy:4:in `<main>'

**Comment by aurel6710** [comment]
I have exactly the same problem :
Successfully installed siriproxy-0.0.1
1 gem installed
Installing ri documentation for siriproxy-0.0.1...
file 'lib' not found
Installing RDoc documentation for siriproxy-0.0.1...
file 'lib' not found

I have try "rvmsudo siriproxy gencert", but it says : siriproxy: Command not found.

**Comment by delrio1110** [comment]
Siriproxy gemcert doesn't work, so  I took Tony Starks idea and created one manually. Now I have Siri proxy up and running and I just got Siri to start my car. It easy if you follow the YouTube vid on how to create a fake ca for siriproxy.

Thanks flash for all your help.

**Comment by flash66** [comment]
file 'lib' not found
Installing RDoc documentation for siriproxy-0.0.1...
file 'lib' not found

You should have a /lib folder inside your siriproxy folder. That contains the siriproxy.rb file to run the gem.

**Comment by flash66** [comment]
That's awesome delrio! What model Viper are you using? I thought i'd pick one up on eBay and do the same. Neat plugin.

**Comment by delrio1110** [comment]
Awesome plug-in!!!!!! I'm using the viper smart start vss3000. The only issue that I'm running into is when I say (start car) Siri will start the car but Siri doesn't come back and state that the car has started( but it does ). Which is fine because it does start,lock and unlock the car, I guess I'll look at the code.

**Comment by nandor690** [comment]
I see that in there but I'm a little confused on how to get it to run the gem. rvmsudo ruby siriproxy.rb wouldn't do nothing. But do I still need to if i already moved the gem into the proper location.
My real problem is I get an error for siriproxy/command_line.rb, which i have posted above.

Thanks 
Nandor690

**Comment by nandor690** [comment]
Ok, I figured out that part of the problem was that I downloaded it instead of cloning it. I just figured cloning was a fancy way of saying download. LOL.
But now I get

git://github.com/chendo/cora.git (at master) is not checked out. Please run `bundle install`

And yes I ran bundle install, I even cloned it from that repository and tried manually installing it. But no matter what I do it says that.
If I run 'siriproxy bundle' it shows it with all the other gems,Gems included by the bundle:
  Fetching source index for http://rubygems.org/
Using rake (0.9.2.2) 
Using libxml-ruby (2.2.2) 
Using CFPropertyList (2.0.17) 
Using cora (0.0.3) from git://github.com/chendo/cora.git (at master) 
Using eventmachine (0.12.10) 
Using uuidtools (2.1.2) 
Using siriproxy (0.0.1) from source at /Users/Nandor690/.rvm/gems/ruby-1.9.3-p0/gems/siriproxy-0.0.1 
Using siriproxy-computer (1.0) from source at ./plugins/siriproxy-computer 
Using bundler (1.0.21) 
Nandor690-Mac:siriproxy kerrykozma$ rvmsudo siriproxy server
Password:
git://github.com/chendo/cora.git (at master) is not checked out. Please run `bundle install`
Anyone else having this problem?

**Comment by jdfwarrior** [comment]
So is there a definite guide of "do this" yet? A lot of people, including myself, seem to be having issues, but the setup instructions haven't been updated, and I haven't seen a clear "this is whats missing from the instructions" and "this is what steps are missing to get it to work"

**Comment by dcinzona** [comment]
I was having a similar problem after bundling - the bin would never be copied to my bin directory so I could never execute it unless I was pointing to the file directly.
I created a symlink in my /usr/bin (or in my case) /opt/bin folder pointing to the ../gems/siriproxy-0.0.1/bin/siriproxy

Now, whenever I build the symlink always points to the latest executable and is globally accessible.  This may not be the best way to do it, but it works for me.  I know, it was a workaround and not actually solving the problem...so it still bugs me a bit that I have to do that...but it works.

**Comment by nandor690** [comment]
I actually got it figured out. I created a partition and did a fresh install of os x lion. followed directions except for creating gencerts as that still don't work, so I created my own but now siriproxy is working.

**Comment by flash66** [comment]
Okay after my 3rd *$#% machine giving the same false gem install of siriproxy-0.3.0.gem (false also with gem install from /pkg) 
Here is a the fix. Regardless what ANYONE says, sometimes rake either does NOT install the gem properly or the needed files to this location: .rvm/gems/ruby-1.9.3-p0@siriproxy/gems/siriproxy-0.3.0 I don't care how many times you run 'rake install' from root or not, This doesn't work for all machines and it's just probably some BS to do with your install of rvm.

Lets keep in mind /.rvm is a hidden folder. Use a free app that acts as a switch to show hidden files in osx's GUI There are many. This will allow you to drag and drop files to .siriproxy and .rvm

Copy your Siriproxy folder contents to this location '.rvm/gems/ruby-1.9.3-p0@siriproxy/gems/siriproxy-0.3.0' and Viola! 'siriproxy Gencerts,bundle,server will magically work!
This has been a real pain in the ass! This took a forensic compare of a working machine to figure out what the hell was going on but here it is.

**Comment by schmooty** [comment]
can someone ( flash you seem to know this one) help me ppppppllleeeeaase. when I run my server and try to use my 4s i get this error:

Starting SiriProxy on port 443..
Create server for iPhone connection
/home/jc/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/eventmachine-0.12.10/lib/em/connection.rb:304:in `block in start_tls': Could not find /home/jc/.siriproxy/server.passless.key for start_tls (EventMachine::FileNotFoundException)
    from /home/jc/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/eventmachine-0.12.10/lib/em/connection.rb:302:in`each'
    from /home/jc/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/eventmachine-0.12.10/lib/em/connection.rb:302:in `start_tls'
    from /home/jc/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/connection/iphone.rb:15:in`post_init'
    from /home/jc/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/eventmachine-0.12.10/lib/em/connection.rb:45:in `block in new'
    from /home/jc/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/eventmachine-0.12.10/lib/em/connection.rb:36:in`instance_eval'
    from /home/jc/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/eventmachine-0.12.10/lib/em/connection.rb:36:in `new'
    from /home/jc/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/eventmachine-0.12.10/lib/eventmachine.rb:1430:in`event_callback'
    from /home/jc/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run_machine'
    from /home/jc/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in`run'
    from /home/jc/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy.rb:16:in `initialize'
    from /home/jc/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/command_line.rb:96:in`new'
    from /home/jc/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/command_line.rb:96:in `start_server'
    from /home/jc/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/command_line.rb:85:in`run_server'
    from /home/jc/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/command_line.rb:37:in `initialize'
    from /home/jc/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/bin/siriproxy:6:in`new'
    from /home/jc/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/bin/siriproxy:6:in `<top (required)>'
    from /home/jc/.rvm/gems/ruby-1.9.3-p0@SiriProxy/bin/siriproxy:19:in`load'
    from /home/jc/.rvm/gems/ruby-1.9.3-p0@SiriProxy/bin/siriproxy:19:in `<main>'

how can i fix this or where is the problem???? i have already confirmed i have both passless crt and key in my siri proxy folder as was advised from a previous post

**Comment by ic0nic** [comment]
start a fresh install of ubuntu 10.11 follow the instructions on https://github.com/ic0nic/The-Four-Little-Pigs-Siri-Proxy

for instructions scroll down

**Comment by elvisimprsntr** [comment]
closed due to inactivity
